sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- 6
- 7
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
- npm run webdriver-update
script:
- npm run e2e
deploy:
  provider: heroku
  api_key:
    secure: UOZhdORrwyjehfy78T3Gs+jpeYXyuKAasmze81wjBU9OM0nA6g6ipSjzaaTLFkMZ5T9pySa8mrqhLUXuVIVe39/fjglUjtoRqPUtCyVEVEcH0bPHwQ62cSzpOukbSrykOjQOHJBja9TUTeDQLJLdw/9nl/bIhm/hvOQ5mky8BCIDFeo/3w4Z0y87sk9Vb8UvoZvvUL51BGkSfHiXfZSW0hN6KelxnH/jbQYCcYvAskmBwnefEJQ9mQY9xq5cqMjLwCC364Ynmut89PuDRqSKLcfg1bvN1YOGgNzDrW6KVXcM7hoT5ptETH098Bdu6DCE2WHRAJKNNXCSn5gESRP7RgebCpgFAXFNygD+YWUCcubsvub0T3Pzkco3zdjVMA3CirhswXnCtmdO+ULA6lyHAHQY2j71l7fy9oqnr2OhalGIlgBAa1aPlNrGAeL9bg+l9Hq12Q6/+4mVax4QnlTVjrFSLm0W8/cMQU1OY6+iyb29eQGRGNm5ph3XL8HbuLkJmT9wCizD7oFVQucJuddd0HZc1ILZ26IRKWDkr9YegG81Gk1Hwr1Y5Gp+jmaM/XlpiCue2z2c4gjP6ZczW8mASKeRjjhjwGCww25Gtagj1apoQNbJDH2gqV4H42TED4okizlyuUVKpVDoy6lxFlb75OTfVGTR+04NfWHft7gQGEE=
  app: angular-js-demo-app
